Repository Interacao-Humano-Computador/2022.2-Lichess, pull requests merged in 2022-11, with the labels that each got.

#5 Create issue template
  .github/ISSUE_TEMPLATE/issue-name.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: documentation

#6 [FEATURE] Ata do dia 10/11
  docs/about_us.md
  docs/atas/ata_10_11.md
  mkdocs.yml
Labels: documentation

#14 [REFAC]: Ajuste das atas
  docs/atas/ata_01_11.md
  docs/atas/ata_15_11.md
Labels: documentation

#19 [REFAC]: correction in minutes
  docs/atas/ata_01_11.md
  docs/atas/ata_10_11.md
  docs/atas/ata_15_11.md
Labels: documentation

#18 [FEAT]: App selected
  docs/atas/ata_01_11.md
  docs/atas/ata_10_11.md
  docs/atas/ata_15_11.md
  docs/index.md
  docs/planejamento/app_selected.md
  docs/planejamento/cronograma.md
  docs/planejamento/images/img-lichess.png
  docs/planejamento/metodologias.md
  docs/planejamento/processo_de_design.md
  docs/planejamento/tools.md
  mkdocs.yml
Labels: documentation

#35 [#28/FEAT]: Adição do documento de aspectos éticos
  docs/analise_requisitos/aspectos_eticos.md
  mkdocs.yml
Labels: documentation

#38 [User Profile/ Personas]
  docs/analise_requisitos/imgs/perfil_usuario/pergunta-1.png
  docs/analise_requisitos/imgs/perfil_usuario/pergunta-10.png
  docs/analise_requisitos/imgs/perfil_usuario/pergunta-11.png
  docs/analise_requisitos/imgs/perfil_usuario/pergunta-12.png
  docs/analise_requisitos/imgs/perfil_usuario/pergunta-2.png
  docs/analise_requisitos/imgs/perfil_usuario/pergunta-5.png
  docs/analise_requisitos/imgs/perfil_usuario/pergunta-6.png
  docs/analise_requisitos/imgs/perfil_usuario/pergunta-8.png
  docs/analise_requisitos/imgs/personas/jorge.jpeg
  docs/analise_requisitos/imgs/personas/ravi.jpeg
  docs/analise_requisitos/imgs/personas/roberta.jpeg
  docs/analise_requisitos/perfil_usuario.md
  docs/analise_requisitos/personas.md
  mkdocs.yml
Labels: enhancement

#36 [#33/REFAC] Ajustes nas legendas e versionamento
  docs/analise_requisitos/aspectos_eticos.md
  docs/apresentacoes.md
  docs/atas/ata_01_11.md
  docs/atas/ata_10_11.md
  docs/atas/ata_15_11.md
  docs/atas/ata_22_11.md
  docs/index.md
  docs/planejamento/app_selected.md
  docs/planejamento/cronograma.md
  docs/planejamento/cronograma_realizado.md
  docs/planejamento/metodologias.md
  docs/planejamento/processo_de_design.md
  docs/planejamento/sites_avaliados.md
  docs/planejamento/sítios_avaliados/resultados_age_telecom.md
  docs/planejamento/sítios_avaliados/resultados_tse.md
  docs/planejamento/tools.md
  mkdocs.yml
  util/padrao_artefato.md
  util/padrao_ata.md
Labels: refactoring

#41 feat: Add document ata 29/11
  docs/atas/ata_29_11.md
  mkdocs.yml
Labels: documentation

#39 [#24/FEAT] Análise das tarefas do usuário
  docs/analise_requisitos/analise_tarefas.md
  docs/analise_requisitos/imgs/hta-1.png
  docs/analise_requisitos/imgs/hta-jogar-partida.png
  docs/img/lucidchart.png
  docs/img/this-person-doesnt-exist.png
  docs/planejamento/tools.md
  mkdocs.yml
Labels: enhancement
